"""init

Revision ID: 304a3fd06ab1
Revises: 
Create Date: 2026-09-15 14:44:48.712943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '304a3fd06ab1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
