"""p2p_gl_domain_model

Revision ID: 5444d20effda
Revises: 304a3fd06ab1
Create Date: 2026-09-15 14:56:56.374296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


revision: str = '5444d20effda'
down_revision: Union[str, None] = '304a3fd06ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_users'))
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_role'), 'app_users', ['role'], unique=False)
    op.create_table('gl_accounts',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('account_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False, comment='asset | liability | equity | revenue | expense'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gl_accounts')),
    sa.UniqueConstraint('account_code', name='uq_gl_accounts_account_code')
    )
    op.create_index(op.f('ix_gl_accounts_account_code'), 'gl_accounts', ['account_code'], unique=False)
    op.create_table('vendors',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('vendor_code', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(length=256), nullable=False),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('bank_account_masked', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False, comment='Blocked by an auditor after a confirmed-fraud finding; new POs/invoices refused.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('vendor_code', name='uq_vendors_vendor_code')
    )
    op.create_index(op.f('ix_vendors_vendor_code'), 'vendors', ['vendor_code'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('actor_user_id', app.models.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False, comment='e.g. invoice.approve, payment.post, period.close, alert.feedback'),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', app.models.types.GUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_users.id'], name=op.f('fk_audit_log_actor_user_id_app_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_correlation_id'), 'audit_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('fiscal_periods',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('period_code', sa.String(length=8), nullable=False, comment="e.g. '2026-09'"),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_by_id', app.models.types.GUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['app_users.id'], name=op.f('fk_fiscal_periods_closed_by_id_app_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_periods')),
    sa.UniqueConstraint('period_code', name='uq_fiscal_periods_period_code')
    )
    op.create_index(op.f('ix_fiscal_periods_status'), 'fiscal_periods', ['status'], unique=False)
    op.create_table('payment_runs',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('run_number', sa.String(length=32), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('initiated_by_id', app.models.types.GUID(), nullable=False),
    sa.Column('approved_by_id', app.models.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['app_users.id'], name=op.f('fk_payment_runs_approved_by_id_app_users')),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['app_users.id'], name=op.f('fk_payment_runs_initiated_by_id_app_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_runs'))
    )
    op.create_index(op.f('ix_payment_runs_run_number'), 'payment_runs', ['run_number'], unique=True)
    op.create_index(op.f('ix_payment_runs_status'), 'payment_runs', ['status'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('vendor_id', app.models.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_by_id', app.models.types.GUID(), nullable=False),
    sa.Column('approved_by_id', app.models.types.GUID(), nullable=True),
    sa.Column('price_tolerance_pct', sa.Float(), nullable=True),
    sa.Column('qty_tolerance_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['app_users.id'], name=op.f('fk_purchase_orders_approved_by_id_app_users')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['app_users.id'], name=op.f('fk_purchase_orders_requested_by_id_app_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_purchase_orders_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('ap_invoices',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', app.models.types.GUID(), nullable=False),
    sa.Column('purchase_order_id', app.models.types.GUID(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('match_status', sa.String(length=32), nullable=False),
    sa.Column('duplicate_check_status', sa.String(length=32), nullable=False),
    sa.Column('duplicate_of_invoice_id', app.models.types.GUID(), nullable=True),
    sa.Column('submitted_by_id', app.models.types.GUID(), nullable=False),
    sa.Column('approved_by_id', app.models.types.GUID(), nullable=True),
    sa.Column('fiscal_period_id', app.models.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['app_users.id'], name=op.f('fk_ap_invoices_approved_by_id_app_users')),
    sa.ForeignKeyConstraint(['duplicate_of_invoice_id'], ['ap_invoices.id'], name=op.f('fk_ap_invoices_duplicate_of_invoice_id_ap_invoices')),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], name=op.f('fk_ap_invoices_fiscal_period_id_fiscal_periods')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_ap_invoices_purchase_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['app_users.id'], name=op.f('fk_ap_invoices_submitted_by_id_app_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_ap_invoices_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ap_invoices'))
    )
    op.create_index(op.f('ix_ap_invoices_duplicate_check_status'), 'ap_invoices', ['duplicate_check_status'], unique=False)
    op.create_index(op.f('ix_ap_invoices_invoice_number'), 'ap_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_ap_invoices_status'), 'ap_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_ap_invoices_vendor_id'), 'ap_invoices', ['vendor_id'], unique=False)
    op.create_index('uq_ap_invoices_vendor_invoice_number_live', 'ap_invoices', ['vendor_id', 'invoice_number'], unique=True, postgresql_where="status != 'voided'")
    op.create_table('goods_receipts',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', app.models.types.GUID(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_by_id', app.models.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_goods_receipts_purchase_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['received_by_id'], ['app_users.id'], name=op.f('fk_goods_receipts_received_by_id_app_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipts'))
    )
    op.create_index(op.f('ix_goods_receipts_purchase_order_id'), 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receipt_number'), 'goods_receipts', ['receipt_number'], unique=True)
    op.create_table('journal_entries',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('entry_number', sa.String(length=32), nullable=False),
    sa.Column('fiscal_period_id', app.models.types.GUID(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='ap_invoice | payment | manual | goods_receipt'),
    sa.Column('source_id', app.models.types.GUID(), nullable=True),
    sa.Column('posted_by_id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_period_id'], ['fiscal_periods.id'], name=op.f('fk_journal_entries_fiscal_period_id_fiscal_periods')),
    sa.ForeignKeyConstraint(['posted_by_id'], ['app_users.id'], name=op.f('fk_journal_entries_posted_by_id_app_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_index(op.f('ix_journal_entries_entry_number'), 'journal_entries', ['entry_number'], unique=True)
    op.create_index(op.f('ix_journal_entries_fiscal_period_id'), 'journal_entries', ['fiscal_period_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_posting_date'), 'journal_entries', ['posting_date'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('purchase_order_id', app.models.types.GUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('quantity_ordered', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gl_account_id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], name=op.f('fk_purchase_order_lines_gl_account_id_gl_accounts')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines'))
    )
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('ap_invoice_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.types.GUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('po_line_id', app.models.types.GUID(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gl_account_id', app.models.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], name=op.f('fk_ap_invoice_lines_gl_account_id_gl_accounts')),
    sa.ForeignKeyConstraint(['invoice_id'], ['ap_invoices.id'], name=op.f('fk_ap_invoice_lines_invoice_id_ap_invoices')),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], name=op.f('fk_ap_invoice_lines_po_line_id_purchase_order_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ap_invoice_lines'))
    )
    op.create_index(op.f('ix_ap_invoice_lines_invoice_id'), 'ap_invoice_lines', ['invoice_id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('goods_receipt_id', app.models.types.GUID(), nullable=False),
    sa.Column('po_line_id', app.models.types.GUID(), nullable=False),
    sa.Column('quantity_received', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('fk_goods_receipt_lines_goods_receipt_id_goods_receipts')),
    sa.ForeignKeyConstraint(['po_line_id'], ['purchase_order_lines.id'], name=op.f('fk_goods_receipt_lines_po_line_id_purchase_order_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_lines'))
    )
    op.create_index(op.f('ix_goods_receipt_lines_goods_receipt_id'), 'goods_receipt_lines', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_lines_po_line_id'), 'goods_receipt_lines', ['po_line_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('journal_entry_id', app.models.types.GUID(), nullable=False),
    sa.Column('gl_account_id', app.models.types.GUID(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.CheckConstraint('(debit_amount > 0 AND credit_amount = 0) OR (credit_amount > 0 AND debit_amount = 0)', name=op.f('ck_journal_lines_debit_xor_credit')),
    sa.ForeignKeyConstraint(['gl_account_id'], ['gl_accounts.id'], name=op.f('fk_journal_lines_gl_account_id_gl_accounts')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_journal_lines_journal_entry_id_journal_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines'))
    )
    op.create_index(op.f('ix_journal_lines_gl_account_id'), 'journal_lines', ['gl_account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('payment_run_id', app.models.types.GUID(), nullable=True),
    sa.Column('invoice_id', app.models.types.GUID(), nullable=False),
    sa.Column('vendor_id', app.models.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['ap_invoices.id'], name=op.f('fk_payments_invoice_id_ap_invoices')),
    sa.ForeignKeyConstraint(['payment_run_id'], ['payment_runs.id'], name=op.f('fk_payments_payment_run_id_payment_runs')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_payments_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_run_id'), 'payments', ['payment_run_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_vendor_id'), 'payments', ['vendor_id'], unique=False)
    op.create_index('uq_payments_invoice_live', 'payments', ['invoice_id'], unique=True, postgresql_where="status IN ('pending', 'posted', 'cleared')")
    op.create_table('audit_alerts',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('payment_id', app.models.types.GUID(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('risk_drivers', sa.JSON(), nullable=False),
    sa.Column('graph_evidence', sa.JSON(), nullable=False),
    sa.Column('model_artifact', sa.String(length=64), nullable=False),
    sa.Column('feedback_status', sa.String(length=32), nullable=False),
    sa.Column('feedback_by_id', app.models.types.GUID(), nullable=True),
    sa.Column('feedback_note', sa.String(length=1024), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_by_id'], ['app_users.id'], name=op.f('fk_audit_alerts_feedback_by_id_app_users')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_audit_alerts_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_alerts'))
    )
    op.create_index(op.f('ix_audit_alerts_dataset'), 'audit_alerts', ['dataset'], unique=False)
    op.create_index(op.f('ix_audit_alerts_feedback_status'), 'audit_alerts', ['feedback_status'], unique=False)
    op.create_index(op.f('ix_audit_alerts_payment_id'), 'audit_alerts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_audit_alerts_transaction_id'), 'audit_alerts', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_alerts_transaction_id'), table_name='audit_alerts')
    op.drop_index(op.f('ix_audit_alerts_payment_id'), table_name='audit_alerts')
    op.drop_index(op.f('ix_audit_alerts_feedback_status'), table_name='audit_alerts')
    op.drop_index(op.f('ix_audit_alerts_dataset'), table_name='audit_alerts')
    op.drop_table('audit_alerts')
    op.drop_index('uq_payments_invoice_live', table_name='payments', postgresql_where="status IN ('pending', 'posted', 'cleared')")
    op.drop_index(op.f('ix_payments_vendor_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_run_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_journal_lines_journal_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_gl_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_goods_receipt_lines_po_line_id'), table_name='goods_receipt_lines')
    op.drop_index(op.f('ix_goods_receipt_lines_goods_receipt_id'), table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index(op.f('ix_ap_invoice_lines_invoice_id'), table_name='ap_invoice_lines')
    op.drop_table('ap_invoice_lines')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_journal_entries_posting_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_fiscal_period_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_number'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_goods_receipts_receipt_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_purchase_order_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index('uq_ap_invoices_vendor_invoice_number_live', table_name='ap_invoices', postgresql_where="status != 'voided'")
    op.drop_index(op.f('ix_ap_invoices_vendor_id'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_status'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_invoice_number'), table_name='ap_invoices')
    op.drop_index(op.f('ix_ap_invoices_duplicate_check_status'), table_name='ap_invoices')
    op.drop_table('ap_invoices')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_payment_runs_status'), table_name='payment_runs')
    op.drop_index(op.f('ix_payment_runs_run_number'), table_name='payment_runs')
    op.drop_table('payment_runs')
    op.drop_index(op.f('ix_fiscal_periods_status'), table_name='fiscal_periods')
    op.drop_table('fiscal_periods')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_correlation_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_vendors_vendor_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_gl_accounts_account_code'), table_name='gl_accounts')
    op.drop_table('gl_accounts')
    op.drop_index(op.f('ix_app_users_role'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
