"""module7_performance_indexes

Revision ID: 7f796bc977a2
Revises: 81cfad276a43
Create Date: 2026-09-15 17:50:12.540378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f796bc977a2'
down_revision: Union[str, None] = '81cfad276a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ap_invoices_status_invoice_date', 'ap_invoices', ['status', 'invoice_date'], unique=False)
    op.create_index('ix_ap_invoices_vendor_id_id', 'ap_invoices', ['vendor_id', 'id'], unique=False)
    op.create_index('ix_audit_alerts_score', 'audit_alerts', ['score'], unique=False, postgresql_ops={'score': 'DESC'})
    op.create_index('ix_payments_invoice_id_id', 'payments', ['invoice_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_invoice_id_id', table_name='payments')
    op.drop_index('ix_audit_alerts_score', table_name='audit_alerts', postgresql_ops={'score': 'DESC'})
    op.drop_index('ix_ap_invoices_vendor_id_id', table_name='ap_invoices')
    op.drop_index('ix_ap_invoices_status_invoice_date', table_name='ap_invoices')
    # ### end Alembic commands ###
